---
permalink: reference-supported-operating-systems.html 
sidebar: sidebar 
keywords: installing, smi-s provider, verify, windows, host, operating systems 
summary: Vor der Installation von SMI-S Provider müssen Sie überprüfen, ob auf dem Windows-Host ein unterstütztes Betriebssystem ausgeführt wird. 
---
= Unterstützte Betriebssystemversionen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/
:pp: &#43;&#43;


[role="lead"]
Wir empfehlen Ihnen, den SMI-S Provider auf einer eigenen, dedizierten virtuellen Windows-Maschine (VM) zu installieren. Diese VM kann sich in derselben Domäne befinden, um eine sichere und komfortable Verwaltung zu ermöglichen.

Vor der Installation von SMI-S Provider müssen Sie überprüfen, ob auf dem Windows-Host ein unterstütztes Betriebssystem ausgeführt wird.

[cols="3*"]
|===
| Betriebssystem | Unterstützte Versionen | Erforderliche Client Software 


 a| 
Windows
 a| 
* Microsoft Windows Server 2025
* Microsoft Windows Server 2022
* Microsoft Windows Server 2019
* Microsoft Windows Server 2016

 a| 
Die Microsoft Visual C++ 2010-Laufzeitbibliotheken werden während der Installation des SMI-S-Providers automatisch installiert. Um mögliche Probleme im Zusammenhang mit Laufzeitbibliotheken zu vermeiden, müssen Sie das Microsoft Visual C++ 2010 Redistributable Package (x86) von folgendem Speicherort installieren: http://www.microsoft.com[]

|===


== Stellen Sie sicher, dass der Hostrechner des Anbieters die Spezifikationen erfüllt.

Zum Ausführen von SMI-S Provider muss der Provider-Hostcomputer die folgenden Spezifikationen erfüllen:

* Der Provider kann nicht direkt auf einem Hyper-V-Knoten installiert werden. Alternativ können Sie es auf einer Hyper-V-VM installieren.
* Der System Center Virtual Machine Manager (SCVMM) darf nicht auf dem Host-Rechner des Anbieters ausgeführt werden.
* Auf dem Host-Rechner des Providers dürfen andere speicherintensive Programme nicht ausgeführt werden.
* Auf dem Provider-Host-Rechner dürfen keine SMI-S-Provider von anderen Anbietern ausgeführt werden.

