---
permalink: reference-clone-snapshot-operations-are-not-allowed.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Probleme bei NetApp SMI-S Provider. 
---
= Klon-/Snapshot-Vorgänge sind nicht zulässig
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Es kann eine Fehlermeldung auftreten, die darauf hinweist, dass Klon- oder Snapshot-Kopiervorgänge nicht zulässig sind, solange ein LUN-Klon-Split-Vorgang ausgeführt wird. Es sollte abgewartet werden, bis der LUN-Klon-Split-Vorgang abgeschlossen ist, danach kann der Vorgang erneut versucht werden.

* *Nachricht*
+
`Clone/Snapshot operations are not allowed while LUN clone split operations are going on in the volume. Please wait for some time and try again.`

* *Beschreibung*
+
Dieser Fehler tritt auf, wenn Sie versuchen, Snapshot-Vorgänge während einer LUN-Klonverteilung auszuführen. Snapshot Vorgänge auf einem Volume, auf dem eine LUN aufgeteilt wird, können nicht durchgeführt werden, wenn im Hintergrund die LUN-Klonabteilung ausgeführt wird.

* *Korrekturmaßnahmen*
+
Versuchen Sie, Ihre Snapshot-Vorgänge durchzuführen, nachdem die LUN aufgeteilt ist.


