---
permalink: reference-entering-passwords-containing-special-characters.html 
sidebar: sidebar 
keywords: troubleshooting, issue, encounter 
summary: Probleme bei NetApp SMI-S Provider. 
---
= Geben Sie Passwörter mit Sonderzeichen ein
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Ausgabe*
+
In englischen Betriebssystemen mit einem Passwort, das Sonderzeichen mit dem enthält `smis` Befehl funktioniert nicht in einer Windows-Umgebung. Dieses Problem wurde bei nicht-englischen Betriebssystemen nicht getestet.

* *Ursache*
+
In Windows gelten die folgenden Zeichen sowie alle Leerzeichen als Sonderzeichen und führen dazu, dass die Eingabe des Kennworts fehlschlägt, wenn das Kennwort nicht in Anführungszeichen eingeschlossen ist:

+
, & ' < > ; {} caret "

* *Korrekturmaßnahmen*
+
Wenn ein Passwort Leerzeichen oder Sonderzeichen enthält, setzen Sie es in doppelte Anführungszeichen (" "), wenn Sie es in verwenden `smis` Befehl. Beachten Sie, dass das Anführungszeichen (") ein Sonderzeichen ist und niemals in Ihrem Kennwort verwendet werden darf.





== Kennwörter mit Sonderzeichen ausstellen

`smis add 1.2.3.4 Administrator "pass word"`

`smis add 1.2.3.4 Administrator "pass&word"`
