---
permalink: reference-smi-s-agent-sizing-and-performance-information.html 
sidebar: sidebar 
keywords: maximum, systems, netapp smi-s provider, help, understand, performance, capability 
summary: Wenn Sie wissen, wie viele Systeme vom NetApp SMI-S-Provider gemanagt werden, können Sie die Performance-Möglichkeiten kennen. 
---
= Sizing und Performance für NetApp SMI-S-Provider
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Wenn Sie wissen, wie viele Systeme vom NetApp SMI-S-Provider gemanagt werden, können Sie die Performance-Möglichkeiten kennen.

*Größe*

NetApp SMI-S Provider kann bis zu folgende Anzahl von Objekten in ONTAP managen:

* 30 Storage Virtual Machines (SVMs) 
* 100 SVMs (ohne Indikationen)
* 10 SVMs (mit Indikationen)
* 1,500 LUNs (pro FlexVol Volume)
* 200 CIFS-Dateifreigaben (pro FlexVol Volume)


Wenn die FlexVol sowohl qtrees als auch Volumes enthält, werden die qtrees als Verzeichnisse angezeigt. Beim Löschen von Volumes sollten Sie darauf achten, dass die qtrees nicht versehentlich gelöscht werden.

*Leistungshinweis*

Bei Konfigurationen mit 5,000 FlexVol Volumes oder 300,000 Snapshot Kopien können im Folgenden Performance-Probleme auftreten `cimcli` Befehl:

* `cimcli ei ONTAP_Snapshot -n root/ontap`
* `cimcli ei ONTAP_SnapshotBasedOnFlexVol -n root/ontap`
* `cimcli ei ONTAP_StorageVolumeStats -n root/ontap`


Das Interoperabilitäts-Matrix-Tool (IMT) enthält die neuesten Informationen zur Dimensionierung und Performance.
